name: example
description: Example for async_builder.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_controller:
    path: ../
  intl: ^0.15.8
  faker: ^1.1.1
  translator:
  provider: ^4.0.0
  flutter_hooks:


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any

flutter:
  uses-material-design: true