include: package:lint/analysis_options.yaml

linter:
  rules:
    # it should be automatic
    prefer_const_constructors: false 

    # occurs even if type was inferred correctly
    type_annotate_public_apis: false 

    # statics are better because they can be used as callbacks
    prefer_constructors_over_static_methods: false 