name: async_controller
description: A library for managing asynchronously loaded data in Flutter. 
version: 1.0.2
homepage: https://github.com/szotp/async_controller

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any